import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>victoria's site</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#6b98e1] to-[#e2eefc]">
       <div className="flex container header__container justify-center">
        <h5>hello, i'm victoria</h5>
        </div>
      </main>
    </>
  );
};

export default Home;
